# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: document.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    "",
    "document.proto",
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x0e\x64ocument.proto"2\n\x1a\x44ocumentRecognitionRequest\x12\x14\n\x0cimage_base64\x18\x01 \x01(\t"*\n\x1b\x44ocumentRecognitionResponse\x12\x0b\n\x03raw\x18\x01 \x01(\t2p\n\x1a\x44ocumentRecognitionService\x12R\n\x13\x44ocumentRecognition\x12\x1b.DocumentRecognitionRequest\x1a\x1c.DocumentRecognitionResponse"\x00\x62\x06proto3',
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "document_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_DOCUMENTRECOGNITIONREQUEST"]._serialized_start = 18
    _globals["_DOCUMENTRECOGNITIONREQUEST"]._serialized_end = 68
    _globals["_DOCUMENTRECOGNITIONRESPONSE"]._serialized_start = 70
    _globals["_DOCUMENTRECOGNITIONRESPONSE"]._serialized_end = 112
    _globals["_DOCUMENTRECOGNITIONSERVICE"]._serialized_start = 114
    _globals["_DOCUMENTRECOGNITIONSERVICE"]._serialized_end = 226
# @@protoc_insertion_point(module_scope)
