"""Add user avatar

Revision ID: 0002
Revises: 0001
Create Date: 2025-10-12 17:24:36.720699

"""

from typing import Sequence, Union

import fastapi_storages.integrations.sqlalchemy
import sqlalchemy as sa
from alembic import op

from src.models.core import s3_backend

# revision identifiers, used by Alembic.
revision: str = "0002"
down_revision: Union[str, None] = "0001"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "avatar",
            fastapi_storages.integrations.sqlalchemy.FileType(
                storage=s3_backend,
            ),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "avatar")
    # ### end Alembic commands ###
